CREATE TABLE homework_comments (
    comment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    comment TEXT NOT NULL,
    user_name TEXT
        REFERENCES classroom_users(username) ON DELETE CASCADE NOT NULL,
    date TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES classroom_users(user_id) ON DELETE CASCADE NOT NULL,
    page_id INTEGER NOT NULL
);